<?php
/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen
Date:			11/11/2017
Description:	Creates the DAL class for  Users table and respective stored procedures

*/



class Projects {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $ProjectID;
	protected $ProjectName;
	protected $ProjectDescription;
	protected $Company;
	protected $Website;

	

	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 5:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4] );
		}
	}


	public function __constructBase() {
		$this->ProjectID = 0;
		$this->ProjectName = "";
		$this->ProjectDescription = "";
		$this->Company = 0;
		$this->Website = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramProjectID,$paramProjectName,$paramProjectDescription,$paramCompany,$paramWebsite) {
		$this->ProjectID = $paramProjectID;
		$this->ProjectName = $paramProjectName;
		$this->ProjectDescription = $paramProjectDescription;
		$this->Company = $paramCompany;
		$this->Website = $paramWebsite;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getProjectID(){
		return $this->ProjectID;
	}
	public function setProjectID($value){
		$this->ProjectID = $value;
	}
	public function getProjectName(){
		return $this->ProjectName;
	}
	public function setProjectName($value){
		$this->ProjectName = $value;
	}
	public function getProjectDescription(){
		return $this->ProjectDescription;
	}
	public function setProjectDescription($value){
		$this->ProjectDescription = $value;
	}
	public function getCompany(){
		return $this->Company;
	}
	public function setCompany($value){
		$this->Company = $value;
	}
	public function getWebsite(){
		return $this->Website;
	}
	public function setWebsite($value){
		$this->Website = $value;
	}



	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Projects_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setProjectID($row['ProjectID']);
		 $this->setProjectName($row['ProjectName']);
		 $this->setProjectDescription($row['ProjectDescription']);
		 $this->setCompany($row['Company']);
		 $this->setWebsite($row['Website']);
		}
	}


	public function save() {
		if ($this->getProjectID() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Projects_Add(?,?,?,?)');
		$arg1 = $this->getProjectName();
		$arg2 = $this->getProjectDescription();
		$arg3 = $this->getCompany();
		$arg4 = $this->getWebsite();
		$stmt->bind_param('ssis',$arg1,$arg2,$arg3,$arg4);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Projects_Update(?,?,?,?,?)');
    $arg1 = $this->getProjectID();
    $arg2 = $this->getProjectName();
		$arg3 = $this->getProjectDescription();
		$arg4 = $this->getCompany();
		$arg5 = $this->getWebsite();
		$stmt->bind_param('issis',$arg1,$arg2,$arg3,$arg4,$arg5);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Projects_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$proj = new Projects($row['ProjectID'],$row['ProjectName'],$row['ProjectDescription'],$row['Company'],$row['Website']);
				$arr[] = $proj;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Projects_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramProjectID,$paramProjectName,$paramProjectDescription,$paramCompany,$paramWebsite) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Projects_Search(?,?,?,?,?)');
		$arg1 = Projects::setNullValue($paramProjectID);
		$arg2 = Projects::setNullValue($paramProjectName);
		$arg3 = Projects::setNullValue($paramProjectDescription);
		$arg4 = Projects::setNullValue($paramCompany);
		$arg5 = Projects::setNullValue($paramWebsite);
		$stmt->bind_param('issis',$arg1,$arg2,$arg3,$arg4,$arg5);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$proj = new Projects($row['ProjectID'],$row['ProjectName'],$row['ProjectDescription'],$row['Company'],$row['Website']);
				$arr[] = $proj;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
?>
