<?php
/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen
Date:			11/12/2017
Description:	Creates the DAL class for  StatusTypes table and respective stored procedures

*/



class StatusTypes {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $StatusTypeID;
	protected $StatusName;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 2:
				self::__constructFull( $argv[0], $argv[1] );
		}
	}


	public function __constructBase() {
		$this->StatusTypeID = 0;
		$this->StatusName = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramStatusTypeID,$paramStatusName) {
		$this->StatusTypeID = $paramStatusTypeID;
		$this->StatusName = $paramStatusName;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getStatusTypeID(){
		return $this->StatusTypeID;
	}
	public function setStatusTypeID($value){
		$this->StatusTypeID = $value;
	}
	public function getStatusName(){
		return $this->StatusName;
	}
	public function setStatusName($value){
		$this->StatusName = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_StatusTypes_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setStatusTypeID($row['StatusTypeID']);
		 $this->setStatusName($row['StatusName']);
		}
	}


	public function save() {
		if ($this->getStatusTypeID() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_StatusTypes_Add(?)');
		$arg1 = $this->getStatusName();
		$stmt->bind_param('s',$arg1);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_StatusTypes_Update(?,?)');
		$arg1 = $this->getStatusTypeID();
		$arg2 = $this->getStatusName();
		$stmt->bind_param('is',$arg1,$arg2);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_StatusTypes_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$StatusTypes = new StatusTypes($row['StatusTypeID'],$row['StatusName']);
				$arr[] = $StatusTypes;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_StatusTypes_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramStatusTypeID,$paramStatusName) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_StatusTypes_Search(?,?)');
		$arg1 = StatusTypes::setNullValue($paramStatusTypeID);
		$arg2 = StatusTypes::setNullValue($paramStatusName);
		$stmt->bind_param('is',$arg1,$arg2);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$StatusTypes = new StatusTypes($row['StatusTypeID'],$row['StatusName']);
				$arr[] = $StatusTypes;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
