<?php
/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen
Date:			11/11/2017
Description:	Creates the DAL class for  Users table and respective stored procedures

*/



class Users {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $UserID;
	protected $Email;
	protected $Username;
	protected $Password;
	protected $FirstName;
	protected $LastName;
	protected $RoleID;
	protected $ImgURL;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 8:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6], $argv[7] );
		}
	}


	public function __constructBase() {
		$this->UserID = 0;
		$this->Email = "";
		$this->Username = "";
		$this->Password = "";
		$this->FirstName = "";
		$this->LastName = "";
		$this->RoleID = 0;
		$this->ImgURL = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramUserID,$paramEmail,$paramUsername,$paramPassword,$paramFirstName,$paramLastName,$paramRoleID,$paramImgURL) {
		$this->UserID = $paramUserID;
		$this->Email = $paramEmail;
		$this->Username = $paramUsername;
		$this->Password = $paramPassword;
		$this->FirstName = $paramFirstName;
		$this->LastName = $paramLastName;
		$this->RoleID = $paramRoleID;
		$this->ImgURL = $paramImgURL;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getUserID(){
		return $this->UserID;
	}
	public function setUserID($value){
		$this->UserID = $value;
	}
	public function getEmail(){
		return $this->Email;
	}
	public function setEmail($value){
		$this->Email = $value;
	}
	public function getUsername(){
		return $this->Username;
	}
	public function setUsername($value){
		$this->Username = $value;
	}
	public function getPassword(){
		return $this->Password;
	}
	public function setPassword($value){
		$this->Password = $value;
	}
	public function getFirstName(){
		return $this->FirstName;
	}
	public function setFirstName($value){
		$this->FirstName = $value;
	}
	public function getLastName(){
		return $this->LastName;
	}
	public function setLastName($value){
		$this->LastName = $value;
	}
	public function getRoleID(){
		return $this->RoleID;
	}
	public function setRoleID($value){
		$this->RoleID = $value;
	}
	public function getImgURL(){
		return $this->ImgURL;
	}
	public function setImgURL($value){
		$this->ImgURL = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Users_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setUserID($row['UserID']);
		 $this->setEmail($row['Email']);
		 $this->setUsername($row['Username']);
		 $this->setPassword($row['Password']);
		 $this->setFirstName($row['FirstName']);
		 $this->setLastName($row['LastName']);
		 $this->setRoleID($row['RoleID']);
		 $this->setImgURL($row['ImgURL']);
		}
	}


	public function save() {
		if ($this->getUserID() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Users_Add(?,?,?,?,?,?,?)');
		$arg1 = $this->getEmail();
		$arg2 = $this->getUsername();
		$arg3 = $this->getPassword();
		$arg4 = $this->getFirstName();
		$arg5 = $this->getLastName();
		$arg6 = $this->getRoleID();
		$arg7 = $this->getImgURL();
		$stmt->bind_param('sssssis',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Users_Update(?,?,?,?,?,?,?,?)');
		$arg1 = $this->getUserID();
		$arg2 = $this->getEmail();
		$arg3 = $this->getUsername();
		$arg4 = $this->getPassword();
		$arg5 = $this->getFirstName();
		$arg6 = $this->getLastName();
		$arg7 = $this->getRoleID();
		$arg8 = $this->getImgURL();
		$stmt->bind_param('isssssis',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Users_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$users = new Users($row['UserID'],$row['Email'],$row['Username'],$row['Password'],$row['FirstName'],$row['LastName'],$row['RoleID'],$row['ImgURL']);
				$arr[] = $users;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Users_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramUserID,$paramEmail,$paramUsername,$paramPassword,$paramFirstName,$paramLastName,$paramRoleID,$paramImgURL) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Users_Search(?,?,?,?,?,?,?,?)');
		$arg1 = Users::setNullValue($paramUserID);
		$arg2 = Users::setNullValue($paramEmail);
		$arg3 = Users::setNullValue($paramUsername);
		$arg4 = Users::setNullValue($paramPassword);
		$arg5 = Users::setNullValue($paramFirstName);
		$arg6 = Users::setNullValue($paramLastName);
		$arg7 = Users::setNullValue($paramRoleID);
		$arg8 = Users::setNullValue($paramImgURL);
		$stmt->bind_param('isssssis',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$users = new Users($row['UserID'],$row['Email'],$row['Username'],$row['Password'],$row['FirstName'],$row['LastName'],$row['RoleID'],$row['ImgURL']);
				$arr[] = $users;
			}
			return $arr;
		}
		else {
			//die("The query yielded zero results.No rows found.");
		}
	}
}
?>
