<?php
/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen
Date:			11/11/2017
Description:	Creates the DAL class for  Users table and respective stored procedures
*/



class NotificationType {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $NotificationTypesID;
	protected $NotificationTypesName;




	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 2:
				self::__constructFull( $argv[0], $argv[1] );
		}
	}


	public function __constructBase() {
		$this->NotificationTypesID = 0;
		$this->NotificationTypesName = "";

	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramNotificationTypesID,$paramNotificationTypesName) {
		$this->NotificationTypesID = $paramNotificationTypesID;
		$this->NotificationTypesName = $paramNotificationTypesName;

	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getNotificationTypesID(){
		return $this->NotificationTypesID;
	}
	public function setNotificationTypesID($value){
		$this->NotificationTypesID = $value;
	}
	public function getNotificationTypesName(){
		return $this->NotificationTypesName;
	}
	public function setNotificationTypesName($value){
		$this->NotificationTypesName = $value;
	}



	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_NotificationTypes_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setNotificationTypesID($row['NotificationTypesID']);
		 $this->setNotificationTypesName($row['NotificationTypesName']);

		}
	}


	public function save() {
		if ($this->getNotificationTypesID() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_NotificationTypes_Add(?)');
		$arg1 = $this->getNotificationTypesName();
		$stmt->bind_param('s',$arg1);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_NotificationTypes_Update(?,?,?,?,?)');
    $arg1 = $this->getNotificationTypesID();
    $arg2 = $this->getNotificationTypesName();
		$stmt->bind_param('is',$arg1,$arg2);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_NotificationTypes_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$proj = new NotificationType($row['NotificationTypesID'],$row['NotificationTypesName']);
				$arr[] = $proj;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_NotificationTypes_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramNotificationTypesID,$paramNotificationTypesName) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_NotificationTypes_Search(?,?,?,?,?)');
		$arg1 = NotificationType::setNullValue($paramNotificationTypesID);
		$arg2 = NotificationType::setNullValue($paramNotificationTypesName);
		$stmt->bind_param('is',$arg1,$arg2);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$proj = new NotificationType($row['NotificationTypesID'],$row['NotificationTypesName']);
				$arr[] = $proj;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
?>
