/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen
Date:			11/12/2017
Description:	Creates the StatusTypes table and respective stored procedures

*/


USE DevData;







CREATE TABLE `DevData`.`StatusTypes` (
StatusTypeID INT AUTO_INCREMENT,
StatusName VARCHAR(100),
CONSTRAINT pk_StatusTypes_StatusTypeID PRIMARY KEY (StatusTypeID)
);





DELIMITER //
CREATE PROCEDURE `DevData`.`usp_StatusTypes_Load`
(
	 IN paramStatusTypeID INT
)
BEGIN
	SELECT
		`StatusTypes`.`StatusTypeID` AS `StatusTypeID`,
		`StatusTypes`.`StatusName` AS `StatusName`
	FROM `StatusTypes`
	WHERE 		`StatusTypes`.`StatusTypeID` = paramStatusTypeID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `DevData`.`usp_StatusTypes_LoadAll`()
BEGIN
	SELECT
		`StatusTypes`.`StatusTypeID` AS `StatusTypeID`,
		`StatusTypes`.`StatusName` AS `StatusName`
	FROM `StatusTypes`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `DevData`.`usp_StatusTypes_Add`
(
	 IN paramStatusName VARCHAR(100)
)
BEGIN
	INSERT INTO `StatusTypes` (StatusName)
	VALUES (paramStatusName);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `DevData`.`usp_StatusTypes_Update`
(
	IN paramStatusTypeID INT,
	IN paramStatusName VARCHAR(100)
)
BEGIN
	UPDATE `StatusTypes`
	SET StatusName = paramStatusName
	WHERE		`StatusTypes`.`StatusTypeID` = paramStatusTypeID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `DevData`.`usp_StatusTypes_Delete`
(
	IN paramStatusTypeID INT
)
BEGIN
	DELETE FROM `StatusTypes`
	WHERE		`StatusTypes`.`StatusTypeID` = paramStatusTypeID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `DevData`.`usp_StatusTypes_Search`
(
	IN paramStatusTypeID INT,
	IN paramStatusName VARCHAR(100)
)
BEGIN
	SELECT
		`StatusTypes`.`StatusTypeID` AS `StatusTypeID`,
		`StatusTypes`.`StatusName` AS `StatusName`
	FROM `StatusTypes`
	WHERE
		COALESCE(StatusTypes.`StatusTypeID`,0) = COALESCE(paramStatusTypeID,StatusTypes.`StatusTypeID`,0)
		AND COALESCE(StatusTypes.`StatusName`,'') = COALESCE(paramStatusName,StatusTypes.`StatusName`,'');
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `DevData`.`usp_Types_LoadByUserID`
(
	 IN paramStatusTypeID INT
)
BEGIN
	SELECT
		`StatusTypes`.`StatusTypeID` AS `StatusTypeID`,
		`StatusTypes`.`StatusName` AS `StatusName`
	FROM `StatusTypes`
	WHERE 		`StatusTypes`.`StatusTypeID` = paramStatusTypeID;
END //
DELIMITER ;
